name: Verify
on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'main'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  ## Analyze
  analyze:
    runs-on: ubuntu-latest
    name: Run static code analysis
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Analyze
        id: build
        run: ./gradlew clean check -x test

  ## Test
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        id: unit-test
        run: ./gradlew clean test -x check

  ## Run
  run:
    name: Run main
    runs-on: ubuntu-latest
    needs: [ analyze, test ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: main
        run: ./gradlew run
        timeout-minutes: 10
